footer-links:
  dribbble:
  email: karasev00@gmail.com
  facebook:
  flickr:
  github: vasiliykarasev
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: vasiliykarasev

google_analytics: UA-24988729-1

url: "vasiliykarasev.github.io"

permalink: /

version: v1.2.0

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed # You might prefer to minify using :compressed

plugins:
      - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    #  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
